// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiX5eivyOBX5E-3BPWPb_MvA7OjFWn8UU',
    appId: '1:1050081373907:web:81b0d4666f721b5825ee26',
    messagingSenderId: '1050081373907',
    projectId: 'unexa-3c465',
    authDomain: 'unexa-3c465.firebaseapp.com',
    storageBucket: 'unexa-3c465.firebasestorage.app',
    measurementId: 'G-YPZG1Q2CNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ26iB7IP-ZWSTYN56maS5BROp3s5Hr18',
    appId: '1:1050081373907:android:472ac3778f8a924425ee26',
    messagingSenderId: '1050081373907',
    projectId: 'unexa-3c465',
    storageBucket: 'unexa-3c465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE_i3XRLgyjsKkr2SCK_0CXayHm8DvW5w',
    appId: '1:1050081373907:ios:6ead0886bcfdcb9225ee26',
    messagingSenderId: '1050081373907',
    projectId: 'unexa-3c465',
    storageBucket: 'unexa-3c465.firebasestorage.app',
    iosBundleId: 'com.unexa.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE_i3XRLgyjsKkr2SCK_0CXayHm8DvW5w',
    appId: '1:1050081373907:ios:6ead0886bcfdcb9225ee26',
    messagingSenderId: '1050081373907',
    projectId: 'unexa-3c465',
    storageBucket: 'unexa-3c465.firebasestorage.app',
    iosBundleId: 'com.unexa.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiX5eivyOBX5E-3BPWPb_MvA7OjFWn8UU',
    appId: '1:1050081373907:web:e47d052e71d9e8ab25ee26',
    messagingSenderId: '1050081373907',
    projectId: 'unexa-3c465',
    authDomain: 'unexa-3c465.firebaseapp.com',
    storageBucket: 'unexa-3c465.firebasestorage.app',
    measurementId: 'G-KTLPJSLCKH',
  );
}
